version: 0.2

phases:
  build:
    commands:
      - dotnet test ./src/LetsDeploy.Tests/LetsDeploy.Tests.csproj
      - dotnet publish -c release -o ./build_output ./src/LetsDeploy/LetsDeploy.csproj
artifacts:
  files:
    - src/LetsDeploy/build_output/*
    - appspec.yml
    - installApp.sh